import type { PackageCatalogEntry } from "./types.js";

function entry(config: PackageCatalogEntry): PackageCatalogEntry {
  return config;
}

/** Authoritative catalog of every public toolkit package that has a playground demo. */
export const PACKAGE_CATALOG: readonly PackageCatalogEntry[] = [
  // ── Foundation ────────────────────────────────────────────────────────
  entry({
    id: "core",
    title: "Core",
    npmPackage: "@ailura/alpinejs-core",
    folder: "core",
    category: "foundation",
    family: "runtime",
    role: "infrastructure",
    surface: "core",
    api: "guardStore · guardMagic · safeWindow",
    summary:
      "Shared infrastructure for every package: registration guards, SSR-safe env helpers, and controller primitives.",
    readmePath: "packages/core/README.md",
    order: 1,
    badges: ["infrastructure"],
    demo: { available: true },
  }),
  entry({
    id: "state-machine",
    title: "State machine",
    npmPackage: "@ailura/alpinejs-state-machine",
    folder: "state-machine",
    category: "foundation",
    family: "runtime",
    role: "foundation",
    surface: "magic",
    api: "$machine",
    summary:
      "N-state machine with a transition graph, guards, and a reactive facade — the engine behind theme, form, and command.",
    readmePath: "packages/state-machine/README.md",
    order: 2,
    badges: ["infrastructure"],
    demo: { available: true },
  }),
  entry({
    id: "env",
    title: "Env",
    npmPackage: "@ailura/alpinejs-env",
    folder: "env",
    category: "primitives",
    family: "environment",
    role: "capability",
    surface: "magic",
    api: "$network · $visibility · $battery · $platform",
    summary: "Network status, page visibility, battery level, and platform detection.",
    readmePath: "packages/env/README.md",
    order: 1,
    badges: ["browser-only"],
    demo: { available: true },
  }),
  entry({
    id: "media",
    title: "Media",
    npmPackage: "@ailura/alpinejs-media",
    folder: "media",
    category: "primitives",
    family: "environment",
    role: "feature",
    surface: "store",
    api: "$store.media",
    summary: "Reactive viewport breakpoints, dimensions, and media feature queries.",
    readmePath: "packages/media/README.md",
    order: 2,
    badges: ["recommended"],
    related: ["sidebar"],
    demo: { available: true },
  }),
  entry({
    id: "lang",
    title: "Lang",
    npmPackage: "@ailura/alpinejs-lang",
    folder: "lang",
    category: "primitives",
    family: "preferences",
    role: "feature",
    surface: "store",
    api: "$store.lang",
    summary: "Detect, query, and change the current application language.",
    readmePath: "packages/lang/README.md",
    order: 1,
    demo: { available: true },
  }),
  entry({
    id: "scroll",
    title: "Scroll",
    npmPackage: "@ailura/alpinejs-scroll",
    folder: "scroll",
    category: "primitives",
    family: "shell",
    role: "feature",
    surface: "store",
    api: "$store.scroll / $scroll",
    summary: "Scroll position tracking, section observer, and handle-based body lock.",
    readmePath: "packages/scroll/README.md",
    order: 1,
    related: ["sidebar"],
    demo: { available: true },
  }),
  entry({
    id: "gesture",
    title: "Gesture",
    npmPackage: "@ailura/alpinejs-gesture",
    folder: "gesture",
    category: "primitives",
    family: "input",
    role: "feature",
    surface: "directive",
    api: "$store.gesture / x-gesture",
    summary: "Headless pointer gesture recognition — tap, swipe, pan, pinch, and long press.",
    readmePath: "packages/gesture/README.md",
    order: 1,
    demo: { available: true },
  }),
  entry({
    id: "keyboard",
    title: "Keyboard",
    npmPackage: "@ailura/alpinejs-keyboard",
    folder: "keyboard",
    category: "primitives",
    family: "input",
    role: "feature",
    surface: "store",
    api: "$store.keyboard",
    summary: "Scoped keyboard shortcut registry with chords, sequences, and conflict resolution.",
    readmePath: "packages/keyboard/README.md",
    order: 2,
    demo: { available: true },
  }),
  entry({
    id: "history",
    title: "History",
    npmPackage: "@ailura/alpinejs-history",
    folder: "history",
    category: "primitives",
    family: "time",
    role: "feature",
    surface: "store",
    api: "$store.history",
    summary: "Headless undo/redo controller with transactions and a configurable limit.",
    readmePath: "packages/history/README.md",
    order: 1,
    demo: { available: true },
  }),
  entry({
    id: "timer",
    title: "Timer",
    npmPackage: "@ailura/alpinejs-timer",
    folder: "timer",
    category: "primitives",
    family: "time",
    role: "feature",
    surface: "magic",
    api: "$timer",
    summary: "Drift-resistant countdown, countup, and stopwatch factories.",
    readmePath: "packages/timer/README.md",
    order: 2,
    demo: { available: true },
  }),
  entry({
    id: "child",
    title: "Child",
    npmPackage: "@ailura/alpinejs-child",
    folder: "child",
    category: "primitives",
    family: "input",
    role: "feature",
    surface: "directive",
    api: "x-child",
    summary: "asChild-style directive that merges the wrapper attributes onto the first child.",
    readmePath: "packages/child/README.md",
    order: 3,
    demo: { available: true },
  }),
  entry({
    id: "transfer",
    title: "Transfer",
    npmPackage: "@ailura/alpinejs-transfer",
    folder: "transfer",
    category: "primitives",
    family: "environment",
    role: "capability",
    surface: "magic",
    api: "$clipboard · $share · $export",
    summary: "Clipboard copy, Web Share API, and programmatic downloads.",
    readmePath: "packages/transfer/README.md",
    order: 3,
    badges: ["browser-only"],
    demo: { available: true },
  }),
  entry({
    id: "selection",
    title: "Selection",
    npmPackage: "@ailura/alpinejs-selection",
    folder: "selection",
    category: "primitives",
    family: "data-entry",
    role: "feature",
    surface: "store",
    api: "$store.selection / $selection",
    summary: "Framework-agnostic selection primitives with single, multiple, and range modes.",
    readmePath: "packages/selection/README.md",
    order: 1,
    related: ["calendar", "collection"],
    demo: { available: true },
  }),
  entry({
    id: "collection",
    title: "Collection",
    npmPackage: "@ailura/alpinejs-collection",
    folder: "collection",
    category: "primitives",
    family: "data-entry",
    role: "feature",
    surface: "store",
    api: "$store.collection / $collection",
    summary: "Filter, sort, group, paginate, and navigate a keyed collection of records.",
    readmePath: "packages/collection/README.md",
    order: 2,
    related: ["selection", "virtual", "command"],
    demo: { available: true },
  }),
  entry({
    id: "calendar",
    title: "Calendar",
    npmPackage: "@ailura/alpinejs-calendar",
    folder: "calendar",
    category: "primitives",
    family: "data-entry",
    role: "feature",
    surface: "store",
    api: "$store.calendar",
    summary: "Month grids, navigation, and single or range date selection.",
    readmePath: "packages/calendar/README.md",
    order: 3,
    related: ["selection"],
    demo: { available: true },
  }),
  entry({
    id: "form",
    title: "Form",
    npmPackage: "@ailura/alpinejs-form",
    folder: "form",
    category: "primitives",
    family: "data-entry",
    role: "feature",
    surface: "store",
    api: "$store.form",
    summary:
      "Headless form state and validation — dirty, touched, valid, async validation, and server error mapping.",
    readmePath: "packages/form/README.md",
    order: 4,
    demo: { available: true },
  }),
  entry({
    id: "toast",
    title: "Toast",
    npmPackage: "@ailura/alpinejs-toast",
    folder: "toast",
    category: "primitives",
    family: "surfaces",
    role: "feature",
    surface: "magic",
    api: "$toast / $store.toast",
    summary: "Headless toast queue with positions, variants, and auto-dismiss.",
    readmePath: "packages/toast/README.md",
    order: 1,
    related: ["notify"],
    demo: { available: true },
  }),
  entry({
    id: "permissions",
    title: "Permissions",
    npmPackage: "@ailura/alpinejs-permissions",
    folder: "permissions",
    category: "primitives",
    family: "permissions",
    role: "foundation",
    surface: "store",
    api: "$store.permissions / $permissions",
    summary: "Unified browser permission registry with a typed adapter contract.",
    readmePath: "packages/permissions/README.md",
    order: 1,
    badges: ["infrastructure"],
    related: ["notify", "geo", "attention"],
    demo: { available: true },
  }),
  entry({
    id: "notify",
    title: "Notify",
    npmPackage: "@ailura/alpinejs-notify",
    folder: "notify",
    category: "primitives",
    family: "permissions",
    role: "capability",
    surface: "magic",
    api: "$notify",
    summary: "Browser notifications and push permission helpers.",
    readmePath: "packages/notify/README.md",
    order: 2,
    badges: ["browser-only"],
    related: ["permissions", "toast"],
    demo: { available: true },
  }),
  entry({
    id: "geo",
    title: "Geo",
    npmPackage: "@ailura/alpinejs-geo",
    folder: "geo",
    category: "primitives",
    family: "permissions",
    role: "capability",
    surface: "store",
    api: "$store.geo",
    summary: "Geolocation coordinates, accuracy, and permission state.",
    readmePath: "packages/geo/README.md",
    order: 3,
    badges: ["browser-only"],
    related: ["permissions"],
    demo: { available: true },
  }),
  entry({
    id: "overlay",
    title: "Overlay",
    npmPackage: "@ailura/alpinejs-overlay",
    folder: "overlay",
    category: "features",
    family: "surfaces",
    role: "feature",
    surface: "store",
    api: "$store.overlay / $overlay",
    summary:
      "Portal root, z-index stack, and overlay registry shared by dialog, menu, tooltip, and command.",
    readmePath: "packages/overlay/README.md",
    order: 1,
    badges: ["infrastructure"],
    related: ["dialog", "menu", "tooltip", "command"],
    demo: { available: true },
  }),
  entry({
    id: "dialog",
    title: "Dialog",
    npmPackage: "@ailura/alpinejs-dialog",
    folder: "dialog",
    category: "features",
    family: "surfaces",
    role: "feature",
    surface: "store",
    api: "$store.dialog",
    // No "focus trap": `DialogController` has no focus management at all — it
    // never moves focus into the panel nor restores it on close. The ARIA
    // helpers and the per-instance `closeOnEscape` / `closeOnOutsideClick` are
    // real, so the summary says what the package does rather than what a
    // dialog plugin is assumed to do.
    summary: "Registry-keyed modal state with ARIA helpers and per-instance close rules.",
    readmePath: "packages/dialog/README.md",
    order: 2,
    related: ["overlay", "scroll"],
    demo: { available: true },
  }),
  entry({
    id: "menu",
    title: "Menu",
    npmPackage: "@ailura/alpinejs-menu",
    folder: "menu",
    category: "features",
    family: "surfaces",
    role: "feature",
    surface: "store",
    api: "$store.menu",
    summary: "Dropdown and context menu state with keyboard navigation and ARIA helpers.",
    readmePath: "packages/menu/README.md",
    order: 3,
    related: ["overlay"],
    demo: { available: true },
  }),
  entry({
    id: "tooltip",
    title: "Tooltip",
    npmPackage: "@ailura/alpinejs-tooltip",
    folder: "tooltip",
    category: "features",
    family: "surfaces",
    role: "feature",
    surface: "store",
    api: "$store.tooltip",
    summary: "Tooltip open/close state with hover and focus delays.",
    readmePath: "packages/tooltip/README.md",
    order: 4,
    related: ["overlay"],
    demo: { available: true },
  }),
  entry({
    id: "tabs",
    title: "Tabs",
    npmPackage: "@ailura/alpinejs-tabs",
    folder: "tabs",
    category: "features",
    family: "disclosure",
    role: "feature",
    surface: "store",
    api: "$store.tabs / $tabs",
    // No "URL query sync": `TabsController` has no network or history surface
    // at all. Arrow-key navigation, roving tabindex and the ARIA wiring are
    // real and are what the package offers.
    summary: "Accessible tabs with arrow-key navigation, roving tabindex and ARIA helpers.",
    readmePath: "packages/tabs/README.md",
    order: 1,
    demo: { available: true },
  }),
  entry({
    id: "accordion",
    title: "Accordion",
    npmPackage: "@ailura/alpinejs-accordion",
    folder: "accordion",
    category: "features",
    family: "disclosure",
    role: "feature",
    surface: "store",
    api: "$store.accordion",
    // "keyboard focus" overstated it: the controller moves a roving
    // `activeItemId` and the `tabindex` that follows it, but never calls
    // `HTMLElement.focus()`, so DOM focus is yours to move.
    summary: "Single or multi-open accordion state with arrow-key navigation and ARIA helpers.",
    readmePath: "packages/accordion/README.md",
    order: 2,
    demo: { available: true },
  }),
  entry({
    id: "command",
    title: "Command",
    npmPackage: "@ailura/alpinejs-command",
    folder: "command",
    category: "features",
    family: "surfaces",
    role: "feature",
    surface: "store",
    api: "$store.command",
    summary: "Spotlight-style command palette with ranked filtering and async execution.",
    readmePath: "packages/command/README.md",
    order: 5,
    related: ["overlay", "keyboard"],
    demo: { available: true },
  }),
  entry({
    id: "carousel",
    title: "Carousel",
    npmPackage: "@ailura/alpinejs-carousel",
    folder: "carousel",
    category: "features",
    family: "media-display",
    role: "feature",
    surface: "store",
    api: "$store.carousel / x-carousel",
    summary: "Accessible carousel store powered by Embla.",
    readmePath: "packages/carousel/README.md",
    order: 1,
    demo: { available: true },
  }),
  entry({
    id: "virtual",
    title: "Virtual",
    npmPackage: "@ailura/alpinejs-virtual",
    folder: "virtual",
    category: "features",
    family: "media-display",
    role: "feature",
    surface: "store",
    api: "$store.virtual / $virtual / x-virtual-scroll",
    summary: "Headless virtual list controller with fixed and variable item sizes.",
    readmePath: "packages/virtual/README.md",
    order: 2,
    demo: { available: true },
  }),
  entry({
    id: "sidebar",
    title: "Sidebar",
    npmPackage: "@ailura/alpinejs-sidebar",
    folder: "sidebar",
    category: "features",
    family: "shell",
    role: "feature",
    surface: "store",
    api: "$store.sidebar",
    summary: "Visibility, overlay, keyboard, and responsive breakpoint state for app shells.",
    readmePath: "packages/sidebar/README.md",
    order: 1,
    related: ["media", "scroll"],
    demo: { available: true },
  }),
  entry({
    id: "theme",
    title: "Theme",
    npmPackage: "@ailura/alpinejs-theme",
    folder: "theme",
    category: "features",
    family: "preferences",
    role: "feature",
    surface: "store",
    api: "$store.theme / $theme",
    summary: "Light, dark, and system color modes with persistence and cross-tab sync.",
    readmePath: "packages/theme/README.md",
    order: 1,
    badges: ["recommended"],
    related: ["state-machine"],
    demo: { available: true },
  }),
  entry({
    id: "attention",
    title: "Attention",
    npmPackage: "@ailura/alpinejs-attention",
    folder: "attention",
    category: "features",
    family: "permissions",
    role: "feature",
    surface: "magic",
    api: "$wakelock · $idle",
    summary: "Screen Wake Lock and Idle Detection for presentations and session-aware UI.",
    readmePath: "packages/attention/README.md",
    order: 1,
    badges: ["browser-only"],
    related: ["permissions"],
    demo: { available: true },
  }),
  entry({
    id: "query",
    title: "Query",
    npmPackage: "@ailura/alpinejs-query",
    folder: "query",
    category: "data",
    family: "query-stack",
    role: "foundation",
    surface: "store",
    api: "$store.query / $query",
    summary: "TanStack-Query-style cache with staleTime, retries, and mutations.",
    readmePath: "packages/query/README.md",
    order: 1,
    badges: ["infrastructure"],
    related: ["query-adapter-alpine", "query-adapter-zustand", "json-api"],
    demo: { available: true },
  }),
  entry({
    id: "query-adapter-alpine",
    title: "Query adapter (Alpine)",
    npmPackage: "@ailura/alpinejs-query-adapter-alpine",
    folder: "query-adapter-alpine",
    category: "data",
    family: "query-stack",
    role: "adapter",
    surface: "core",
    api: "alpineStoreQueryPlugin",
    summary: "Alpine.reactive-backed state adapter for the query cache.",
    readmePath: "packages/query-adapter-alpine/README.md",
    order: 3,
    badges: ["adapter"],
    related: ["query"],
    requires: ["query"],
    demo: { available: true },
  }),
  entry({
    id: "query-adapter-zustand",
    title: "Query adapter (Zustand)",
    npmPackage: "@ailura/alpinejs-query-adapter-zustand",
    folder: "query-adapter-zustand",
    category: "data",
    family: "query-stack",
    role: "adapter",
    surface: "core",
    api: "createZustandStoreAdapter · createQueryPlugin",
    summary: "Zustand-backed state adapter: every cache publish lands in a zustand/vanilla store.",
    readmePath: "packages/query-adapter-zustand/README.md",
    order: 4,
    badges: ["adapter"],
    related: ["query", "query-adapter-alpine"],
    requires: ["query"],
    demo: { available: true },
  }),
  entry({
    id: "query-adapter-nanostores",
    title: "Query adapter (Nanostores)",
    npmPackage: "@ailura/alpinejs-query-adapter-nanostores",
    folder: "query-adapter-nanostores",
    category: "data",
    family: "query-stack",
    role: "adapter",
    surface: "core",
    api: "createNanostoresStoreAdapter · createQueryPlugin",
    summary:
      "Nanostores-backed state adapter: every cache publish lands in an atom you can subscribe to.",
    readmePath: "packages/query-adapter-nanostores/README.md",
    order: 5,
    badges: ["adapter"],
    related: ["query", "query-adapter-alpine", "query-adapter-zustand"],
    requires: ["query"],
    demo: { available: true },
  }),
  entry({
    id: "json-api",
    title: "JSON:API",
    npmPackage: "@ailura/alpinejs-json-api",
    folder: "json-api",
    category: "data",
    family: "query-stack",
    role: "feature",
    surface: "store",
    api: "$store.jsonApi",
    summary: "Typed JSON:API client with resource schemas and compound document parsing.",
    readmePath: "packages/json-api/README.md",
    order: 2,
    related: ["query"],
    demo: { available: true },
  }),
] as const;
